version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: cheers-up-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: hanana0627/cheers-up-redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: cheers-up-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: hanana0627/cheers-up-database
    environment:
      - MARIADB_DATABASE=cheers-up
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"
